apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # Replace with your actual API key: echo -n "your-api-key" | base64
  openai-key: c2stcHJvai1IUFJHdXhCLUpHZTFfR21UY0dwbkliSGhrSG14RldHLVNBV3RtWnBpRjdmMnRJY2tvNTlfZ0szRFVJR1ZMVGpNTlo3LUp3RDRVSFQzQmxia0ZKY2VUM1FRcERZTlVZTDZobUNteXFyWnhxbWVVbTgtWkJEMGVKd3N4ZFFCWW55T190NDBMLVZiTHRPNGZ2Z2doUkdvRkFRdWo4OEE=