apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # Replace with your actual API key: echo -n "your-api-key" | base64
  openai-key: WU9VUi1BUEktS0VZLUhFUkU=