apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: edtech
  labels:
    app: chromadb
    component: vectordb
spec:
  type: ClusterIP  # Internal service only
  selector:
    app: chromadb
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP  # Stick sessions to same pod