apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: default
  labels:
    app: chromadb
    component: vectordb
spec:
  replicas: 1  # ChromaDB should run as single instance with persistent storage
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
        component: vectordb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: "/chroma/chroma"
        - name: ANONYMIZED_TELEMETRY
          value: "FALSE"
        - name: ALLOW_RESET
          value: "FALSE"  # Prevent accidental data deletion
        volumeMounts:
        - name: chroma-storage
          mountPath: /chroma/chroma
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: chroma-storage
        persistentVolumeClaim:
          claimName: chroma-pvc