apiVersion: apps/v1
kind: Deployment
metadata:
  name: edtech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edtech-frontend
  template:
    metadata:
      labels:
        app: edtech-frontend
    spec:
      containers:
      - name: frontend
        image: edtechacr.azurecr.io/edtech-frontend:v1
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://quiz-generator-service"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5