apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-generator
  template:
    metadata:
      labels:
        app: quiz-generator
    spec:
      containers:
      - name: quiz-generator
        image: edtechacr.azurecr.io/quiz-generator:v1
        ports:
        - containerPort: 8082
        env:
        - name: CHROMADB_HOST
          value: "chromadb-service"
        - name: CHROMADB_PORT
          value: "8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/quiz/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/quiz/health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5