spring:
  application:
    name: edtech-AIbackend
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000
      embedding:
        options:
          model: text-embedding-ada-002
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        api-key: ${QDRANT_API_KEY:}
        collection-name: edtech-quiz
        initialize-schema: true

server:
  port: 8081

pdf:
  storage:
    path: ./

logging:
  level:
    com.edtech.edtech_aibackend: INFO
    org.springframework.web: INFO
